// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";

export type GroupNode = { id: string, label: string, parentId: string | null, color?: string, facadeModuleIds: Array<string>, 
/**
 * Free-form labels from `tags:` in `*.group.md`. Layering rules may forbid
 * importing any group carrying a given tag.
 */
tags: Array<string>, 
/**
 * Facade module id → tags that **replace** this group's for imports that
 * target that facade, so one group can export a tagged and an untagged
 * entry point. Only facades with an explicit `tags:` appear here.
 */
facadeTags: { [key in string]?: Array<string> }, disconnectedByDefault: boolean, disconnectedModuleIds: Array<string>, annotation?: Annotation, architectureDoc?: string, };
