// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticKind } from "./DiagnosticKind";
import type { Severity } from "./Severity";

export type Diagnostic = { id: string, severity: Severity, kind: DiagnosticKind, message: string, moduleId?: string, edgeId?: string, unresolvedTarget?: string, };
