// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeKind } from "./EdgeKind";

export type Edge = { id: string, source: string, target: string, kind: EdgeKind, trigger: string, isViolation: boolean, };
