// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModuleMetrics = { loc: number, 
/**
 * Relative activity: (lines added + deleted) / max(loc, 1) over the git window.
 */
churn?: number, 
/**
 * Bugspots time-weighted risk score over the git window.
 */
bugRisk?: number, 
/**
 * Bug-fix commits touching this module in the git window.
 */
fixCommits?: number, };
