// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { Edge } from "./Edge";
import type { GroupNode } from "./GroupNode";
import type { ModuleNode } from "./ModuleNode";

export type ProjectGraph = { version: number, root: string, groups: Array<GroupNode>, modules: Array<ModuleNode>, edges: Array<Edge>, diagnostics: Array<Diagnostic>, };
